---
- name: create openstack infra
  gather_facts: False
  hosts: localhost
  roles:
   - osp-servers

- name: get openstack server details
  #collections:
  # - openstack.cloud
  openstack.cloud.server_info:
    cloud: 'openstack'
    server: "{{ item.name }}"
   #server: *
    filters:
     vm_state: active 
  loop:
   "{{ osp_servers }}"
  register: server_openstack

- debug:
   var: server_openstack

- meta: end_play
- name: creating in-memory inventory from openstack
  add_host:
   name:
   group:
   ansible_user: 'cloud-user'
   ansible_ssh_private_key_file: '~/.ssh/openstack.pem'

- name: deploying app layer
  hosts: app
  become: true
  roles:
   - app-tier
  tags:
   - app_dep 
   - all

- name: deploying app layer
  hosts: app
  become: true
  roles:
   - lb-tier
  tags:
   - lb_dep 
   - all

- name: deploying app layer
  hosts: app
  become: true
  roles:
   - db-tier
  tags:
   - all
   - db_dep 

- name: run smoketest
  hosts: smoketest
  roles:
   - smoketest
  tags:
   - all
   - smoketest 
