---
- name: create openstack infra
  gather_facts: False
  hosts: localhost
  roles:
   - osp-servers
  tags:
   - all
   - delete_servers 

- name: deploying db layer
  hosts: appdbs
  become: true
  roles:
   - db-tier
  tags:
   - all
   - db_dep 

- name: deploying app layer
  hosts: apps
  become: true
  roles:
   - app-tier
  tags:
   - app_dep 
   - all

- name: deploying frontend layer
  hosts: frontends
  become: true
  roles:
   - lb-tier
  tags:
   - lb_dep 
   - all

- name: run smoketest on app and db
  hosts: apps:appdbs 
  roles:
   - smoketest
  tags:
   - all
   - smoketest_app_db

#- name: run smoketest on apps
#  hosts: apps
#  roles:
#   - smoketest
#  tags:
#   - all
#   - smoketest_app
