---
- name: deploying db layer
  hosts: appdbs
  become: true
  roles:
   - db-tier
  tags:
   - all
   - db_dep

- name: deploying app layer
  hosts: apps
  become: true
  roles:
   - app-tier
  tags:
   - app_dep
   - all

- name: deploying frontend layer
  hosts: frontends
  become: true
  roles:
   - lb-tier
  tags:
   - lb_dep
   - all

