---
- name: create openstack infra
  gather_facts: False
  hosts: localhost 
  roles:
   - role: osp-servers
     tags: fetch_dynamic_inventory_os
  tags:
   - all

- name: run smoketest for apps
  hosts: frontends 
  roles:
   - smoketest 
  register: smoke_result

- name: delete infra in case smoketest fails
  include: site-osp-delete.yml
  when: smoke_result.stdout.find('alive') != 1
