---
- openstack.cloud.server_info:
    cloud: 'openstack'
    server: '*'
    filters:
     vm_state: active
  register: server_openstack
  tags:
   - test_server_info

- name: create in memory inventory for db
  add_host:
   name: "{{ item.public_v4 }}"
   group: "{{ item.metadata.group }}"
   ansible_user: 'cloud-user'
   ansible_ssh_private_key_file: '~/.ssh/openstack.pem'
  loop:
   "{{ server_openstack.openstack_servers }}"
  register: inv_db
  tags:
   - test_server_info
