---
- name: enable the repo
  yum_repository:
    name: epel
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    gpgcheck: no
    description: EPEL YUM repo

- name: update the repo
  yum:
   name: '*'
   state: latest
   enablerepo: "epel,ol7_latest"

- name: Install load balancer packages
  package:
    name: "{{ load_balancer_packages }}"
    state: present

- name: Configure haproxy load balancing
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart_haproxy

- name: Enable Haproxy
  service:
    name: haproxy
    state: started
    enabled: true

