---
- name: fix the release server version 
  file:
   path: /etc/yum/vars/releasever
   state: touch
   mode: 0666

- name: fix the release server version 
  command:
    cmd: echo 7 >> /etc/yum/vars/releasever

- name: enable the repo
  yum_repository:
    name: epel
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    gpgcheck: no
    description: EPEL YUM repo

- name: copy repo file
  copy:
   src: open_ans-tower-lab-ng.repo
   dest: /etc/yum.repos.d/open_ans-tower-lab-ng.repo

- name: update the repo
  yum:
   name: '*'
   state: latest
   skip_broken: True
   ignore_errors: True

- name: Install load balancer packages
  package:
    name: "{{ load_balancer_packages }}"
    state: present

- name: Configure haproxy load balancing
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart_haproxy

- name: Enable Haproxy
  service:
    name: haproxy
    state: started
    enabled: true

